// flow-typed signature: e968c106afea90bea4aefdf31433e406
// flow-typed version: <<STUB>>/electron_v^5.0.1/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron/cli' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/accessibility_test_runner/accessibility_test_runner_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/accessibility/accessibility_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/accessibility/ARIAProperties' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/animation/animation_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/application_test_runner/application_test_runner_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/audits2_test_runner/audits2_test_runner_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/audits2_worker' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/audits2_worker/audits2_worker_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/audits2/audits2_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/bindings_test_runner/bindings_test_runner_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/browser_debugger/browser_debugger_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/changes/changes_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/cm_modes/cm_modes_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/cm/cm_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/color_picker/color_picker_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/console_test_runner/console_test_runner_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/console/console_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/cookie_table/cookie_table_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/coverage_test_runner/coverage_test_runner_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/coverage/coverage_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/cpu_profiler_test_runner/cpu_profiler_test_runner_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/data_grid_test_runner/data_grid_test_runner_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/data_grid/data_grid_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/device_mode_test_runner/device_mode_test_runner_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/devices/devices_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/devtools_app' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/devtools_compatibility' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/devtools_extension_api' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/diff/diff_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/elements_test_runner/elements_test_runner_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/elements/elements_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/emulated_devices/emulated_devices_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/event_listeners/event_listeners_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/extensions_test_runner/extensions_test_runner_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/formatter_worker' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/formatter/formatter_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/har_importer/har_importer_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/heap_profiler_test_runner/heap_profiler_test_runner_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/heap_snapshot_model/heap_snapshot_model_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/heap_snapshot_worker' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/heap_snapshot_worker/heap_snapshot_worker_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/help/help_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/inline_editor/inline_editor_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/inspector' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/InspectorBackendCommands' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/integration_test_runner' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/javascript_metadata/javascript_metadata_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/js_app' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/js_profiler/js_profiler_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/layer_viewer/layer_viewer_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/layers_test_runner/layers_test_runner_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/layers/layers_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/network_test_runner/network_test_runner_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/network/network_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/node_app' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/node_debugger/node_debugger_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/object_ui/object_ui_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/perf_ui/perf_ui_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/performance_monitor/performance_monitor_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/performance_test_runner/performance_test_runner_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/product_registry_impl/product_registry_impl_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/profiler/profiler_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/protocol_monitor/protocol_monitor_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/quick_open/quick_open_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/resources/resources_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/sdk_test_runner/sdk_test_runner_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/search/search_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/security_test_runner/security_test_runner_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/security/security_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/settings/settings_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/shell' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/snippets/snippets_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/source_frame/source_frame_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/sources_test_runner/sources_test_runner_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/sources/sources_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/SupportedCSSProperties' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/Tests' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/text_editor/text_editor_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/timeline_model/timeline_model_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/timeline/timeline_module' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/toolbox' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/worker_app' {
  declare module.exports: any;
}

declare module 'electron/dist/resources/inspector/workspace_diff/workspace_diff_module' {
  declare module.exports: any;
}

declare module 'electron/install' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron/cli.js' {
  declare module.exports: $Exports<'electron/cli'>;
}
declare module 'electron/dist/resources/inspector/accessibility_test_runner/accessibility_test_runner_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/accessibility_test_runner/accessibility_test_runner_module'>;
}
declare module 'electron/dist/resources/inspector/accessibility/accessibility_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/accessibility/accessibility_module'>;
}
declare module 'electron/dist/resources/inspector/accessibility/ARIAProperties.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/accessibility/ARIAProperties'>;
}
declare module 'electron/dist/resources/inspector/animation/animation_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/animation/animation_module'>;
}
declare module 'electron/dist/resources/inspector/application_test_runner/application_test_runner_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/application_test_runner/application_test_runner_module'>;
}
declare module 'electron/dist/resources/inspector/audits2_test_runner/audits2_test_runner_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/audits2_test_runner/audits2_test_runner_module'>;
}
declare module 'electron/dist/resources/inspector/audits2_worker.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/audits2_worker'>;
}
declare module 'electron/dist/resources/inspector/audits2_worker/audits2_worker_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/audits2_worker/audits2_worker_module'>;
}
declare module 'electron/dist/resources/inspector/audits2/audits2_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/audits2/audits2_module'>;
}
declare module 'electron/dist/resources/inspector/bindings_test_runner/bindings_test_runner_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/bindings_test_runner/bindings_test_runner_module'>;
}
declare module 'electron/dist/resources/inspector/browser_debugger/browser_debugger_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/browser_debugger/browser_debugger_module'>;
}
declare module 'electron/dist/resources/inspector/changes/changes_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/changes/changes_module'>;
}
declare module 'electron/dist/resources/inspector/cm_modes/cm_modes_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/cm_modes/cm_modes_module'>;
}
declare module 'electron/dist/resources/inspector/cm/cm_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/cm/cm_module'>;
}
declare module 'electron/dist/resources/inspector/color_picker/color_picker_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/color_picker/color_picker_module'>;
}
declare module 'electron/dist/resources/inspector/console_test_runner/console_test_runner_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/console_test_runner/console_test_runner_module'>;
}
declare module 'electron/dist/resources/inspector/console/console_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/console/console_module'>;
}
declare module 'electron/dist/resources/inspector/cookie_table/cookie_table_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/cookie_table/cookie_table_module'>;
}
declare module 'electron/dist/resources/inspector/coverage_test_runner/coverage_test_runner_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/coverage_test_runner/coverage_test_runner_module'>;
}
declare module 'electron/dist/resources/inspector/coverage/coverage_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/coverage/coverage_module'>;
}
declare module 'electron/dist/resources/inspector/cpu_profiler_test_runner/cpu_profiler_test_runner_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/cpu_profiler_test_runner/cpu_profiler_test_runner_module'>;
}
declare module 'electron/dist/resources/inspector/data_grid_test_runner/data_grid_test_runner_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/data_grid_test_runner/data_grid_test_runner_module'>;
}
declare module 'electron/dist/resources/inspector/data_grid/data_grid_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/data_grid/data_grid_module'>;
}
declare module 'electron/dist/resources/inspector/device_mode_test_runner/device_mode_test_runner_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/device_mode_test_runner/device_mode_test_runner_module'>;
}
declare module 'electron/dist/resources/inspector/devices/devices_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/devices/devices_module'>;
}
declare module 'electron/dist/resources/inspector/devtools_app.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/devtools_app'>;
}
declare module 'electron/dist/resources/inspector/devtools_compatibility.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/devtools_compatibility'>;
}
declare module 'electron/dist/resources/inspector/devtools_extension_api.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/devtools_extension_api'>;
}
declare module 'electron/dist/resources/inspector/diff/diff_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/diff/diff_module'>;
}
declare module 'electron/dist/resources/inspector/elements_test_runner/elements_test_runner_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/elements_test_runner/elements_test_runner_module'>;
}
declare module 'electron/dist/resources/inspector/elements/elements_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/elements/elements_module'>;
}
declare module 'electron/dist/resources/inspector/emulated_devices/emulated_devices_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/emulated_devices/emulated_devices_module'>;
}
declare module 'electron/dist/resources/inspector/event_listeners/event_listeners_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/event_listeners/event_listeners_module'>;
}
declare module 'electron/dist/resources/inspector/extensions_test_runner/extensions_test_runner_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/extensions_test_runner/extensions_test_runner_module'>;
}
declare module 'electron/dist/resources/inspector/formatter_worker.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/formatter_worker'>;
}
declare module 'electron/dist/resources/inspector/formatter/formatter_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/formatter/formatter_module'>;
}
declare module 'electron/dist/resources/inspector/har_importer/har_importer_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/har_importer/har_importer_module'>;
}
declare module 'electron/dist/resources/inspector/heap_profiler_test_runner/heap_profiler_test_runner_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/heap_profiler_test_runner/heap_profiler_test_runner_module'>;
}
declare module 'electron/dist/resources/inspector/heap_snapshot_model/heap_snapshot_model_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/heap_snapshot_model/heap_snapshot_model_module'>;
}
declare module 'electron/dist/resources/inspector/heap_snapshot_worker.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/heap_snapshot_worker'>;
}
declare module 'electron/dist/resources/inspector/heap_snapshot_worker/heap_snapshot_worker_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/heap_snapshot_worker/heap_snapshot_worker_module'>;
}
declare module 'electron/dist/resources/inspector/help/help_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/help/help_module'>;
}
declare module 'electron/dist/resources/inspector/inline_editor/inline_editor_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/inline_editor/inline_editor_module'>;
}
declare module 'electron/dist/resources/inspector/inspector.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/inspector'>;
}
declare module 'electron/dist/resources/inspector/InspectorBackendCommands.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/InspectorBackendCommands'>;
}
declare module 'electron/dist/resources/inspector/integration_test_runner.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/integration_test_runner'>;
}
declare module 'electron/dist/resources/inspector/javascript_metadata/javascript_metadata_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/javascript_metadata/javascript_metadata_module'>;
}
declare module 'electron/dist/resources/inspector/js_app.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/js_app'>;
}
declare module 'electron/dist/resources/inspector/js_profiler/js_profiler_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/js_profiler/js_profiler_module'>;
}
declare module 'electron/dist/resources/inspector/layer_viewer/layer_viewer_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/layer_viewer/layer_viewer_module'>;
}
declare module 'electron/dist/resources/inspector/layers_test_runner/layers_test_runner_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/layers_test_runner/layers_test_runner_module'>;
}
declare module 'electron/dist/resources/inspector/layers/layers_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/layers/layers_module'>;
}
declare module 'electron/dist/resources/inspector/network_test_runner/network_test_runner_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/network_test_runner/network_test_runner_module'>;
}
declare module 'electron/dist/resources/inspector/network/network_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/network/network_module'>;
}
declare module 'electron/dist/resources/inspector/node_app.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/node_app'>;
}
declare module 'electron/dist/resources/inspector/node_debugger/node_debugger_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/node_debugger/node_debugger_module'>;
}
declare module 'electron/dist/resources/inspector/object_ui/object_ui_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/object_ui/object_ui_module'>;
}
declare module 'electron/dist/resources/inspector/perf_ui/perf_ui_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/perf_ui/perf_ui_module'>;
}
declare module 'electron/dist/resources/inspector/performance_monitor/performance_monitor_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/performance_monitor/performance_monitor_module'>;
}
declare module 'electron/dist/resources/inspector/performance_test_runner/performance_test_runner_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/performance_test_runner/performance_test_runner_module'>;
}
declare module 'electron/dist/resources/inspector/product_registry_impl/product_registry_impl_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/product_registry_impl/product_registry_impl_module'>;
}
declare module 'electron/dist/resources/inspector/profiler/profiler_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/profiler/profiler_module'>;
}
declare module 'electron/dist/resources/inspector/protocol_monitor/protocol_monitor_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/protocol_monitor/protocol_monitor_module'>;
}
declare module 'electron/dist/resources/inspector/quick_open/quick_open_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/quick_open/quick_open_module'>;
}
declare module 'electron/dist/resources/inspector/resources/resources_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/resources/resources_module'>;
}
declare module 'electron/dist/resources/inspector/sdk_test_runner/sdk_test_runner_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/sdk_test_runner/sdk_test_runner_module'>;
}
declare module 'electron/dist/resources/inspector/search/search_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/search/search_module'>;
}
declare module 'electron/dist/resources/inspector/security_test_runner/security_test_runner_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/security_test_runner/security_test_runner_module'>;
}
declare module 'electron/dist/resources/inspector/security/security_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/security/security_module'>;
}
declare module 'electron/dist/resources/inspector/settings/settings_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/settings/settings_module'>;
}
declare module 'electron/dist/resources/inspector/shell.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/shell'>;
}
declare module 'electron/dist/resources/inspector/snippets/snippets_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/snippets/snippets_module'>;
}
declare module 'electron/dist/resources/inspector/source_frame/source_frame_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/source_frame/source_frame_module'>;
}
declare module 'electron/dist/resources/inspector/sources_test_runner/sources_test_runner_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/sources_test_runner/sources_test_runner_module'>;
}
declare module 'electron/dist/resources/inspector/sources/sources_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/sources/sources_module'>;
}
declare module 'electron/dist/resources/inspector/SupportedCSSProperties.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/SupportedCSSProperties'>;
}
declare module 'electron/dist/resources/inspector/Tests.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/Tests'>;
}
declare module 'electron/dist/resources/inspector/text_editor/text_editor_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/text_editor/text_editor_module'>;
}
declare module 'electron/dist/resources/inspector/timeline_model/timeline_model_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/timeline_model/timeline_model_module'>;
}
declare module 'electron/dist/resources/inspector/timeline/timeline_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/timeline/timeline_module'>;
}
declare module 'electron/dist/resources/inspector/toolbox.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/toolbox'>;
}
declare module 'electron/dist/resources/inspector/worker_app.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/worker_app'>;
}
declare module 'electron/dist/resources/inspector/workspace_diff/workspace_diff_module.js' {
  declare module.exports: $Exports<'electron/dist/resources/inspector/workspace_diff/workspace_diff_module'>;
}
declare module 'electron/index' {
  declare module.exports: $Exports<'electron'>;
}
declare module 'electron/index.js' {
  declare module.exports: $Exports<'electron'>;
}
declare module 'electron/install.js' {
  declare module.exports: $Exports<'electron/install'>;
}
