// flow-typed signature: 373db3c20428fdd0dfcce15eb520d4e2
// flow-typed version: <<STUB>>/heroku-ssl-redirect_v^0.0.4/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'heroku-ssl-redirect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'heroku-ssl-redirect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'heroku-ssl-redirect/index' {
  declare module.exports: $Exports<'heroku-ssl-redirect'>;
}
declare module 'heroku-ssl-redirect/index.js' {
  declare module.exports: $Exports<'heroku-ssl-redirect'>;
}
