// flow-typed signature: da7342d67f2ca9ae38ce78defa323ca9
// flow-typed version: <<STUB>>/react-recaptcha_v^2.3.5/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-recaptcha'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-recaptcha' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-recaptcha/dist/react-recaptcha' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-recaptcha/dist/react-recaptcha.js' {
  declare module.exports: $Exports<'react-recaptcha/dist/react-recaptcha'>;
}
